baseurl = "http://nishanttotla.github.io/"
languageCode = "en-us"
title = "nRT"
pygmentsUseClasses = true
theme = "skeleton"
[params]
  description = "Nishant's Hugo Website"
  author = "Nishant Totla"
  authorDescription = "My name is Nishant Totla and I am an engineer. I love the outdoors and adventure. I like to talk about social justice."
  siteDescriptors = ["blog", "outdoors", "adventure", "programming", "software", "Nishant Totla", "Nishant", "Totla"]
  authorTwitter = "nishanttotla"
  authorFacebook = "nishanttotla"
  authorGithub = "nishanttotla"
  authorLinkedin = "nishanttotla"
  authorGoogleplus = "nishanttotla"
  coverImage = "/images/nishant.jpg"
  authorSignature = "nRT"