baseurl = "http://blog.ankush.io/"
languageCode = "en-us"
title = "Ankush's Blog"
pygmentsUseClasses = true
theme = "skeleton"
[permalinks]
  articles = "/:title/"
[params]
  description = "Ankush's Blog"
  author = "Ankush Agarwal"
  authorDescription = "Ankush is a 20-something year old programmer based out of the San Francisco Bay Area"
  siteDescriptors = ["blog", "design", "distributed systems", "programming", "software", "Ankush Agarwal", "Ankush", "Agarwal"]
  authorTwitter = "ankushio"
  authorFacebook = "ankushagarwal11"
  authorGithub = "ankushagarwal"
  authorLinkedin = "ankushagarwal11"
  authorGoogleplus = "ankushagarwal11"
  coverImage = "http://www.gravatar.com/avatar/54525f2e6d6db4473f0fb264a8a5d995?s=300"
  authorSignature = "Ankush"
