baseurl = "http://prakhar.me/"
languageCode = "en-us"
title = "nRT"
pygmentsUseClasses = true
theme = "skeleton"
[params]
  description = "Nishant's Hugo Website"
  author = "Nishant Totla"
  authorTwitter = "nishanttotla"
  authorFacebook = "nishanttotla"
  coverImage = "/images/nishant.jpg"
  authorSignature = "nRT"